name: ie_network_2027
services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ienetwork
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ie_network_2027
volumes:
  db_data:
networks:
  ie_network_2027:
    driver: bridge
